import {Oswald} from "next/font/google";
import "./globals.css"

const font = Oswald({
  subsets: ["latin"]
})

export const metadata = {
  title: "Gleamify",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${font.className}`}>
        {children}
      </body>
    </html>
  );
}
