import {Cormorant_Garamond} from "next/font/google";
import "./globals.css"
import Header from "@/components/header";
import Footer from "@/components/footer";

const font = Cormorant_Garamond({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
})

export const metadata = {
  title: "Gleamify",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${font.className}`}>
      <Header />
        {children}
      <Footer />
      </body>
    </html>
  );
}
